enum TRPCs
{
		// Client -> Server
	RPC_TRADER_MOD_IS_LOADED = 35466,
	RPC_BUY,
	RPC_SELL,
	RPC_APPRAISE_SELL,


	// Server -> Client
	RPC_SEND_TRADER_CURRENCYNAME_ENTRY,
	RPC_SEND_TRADER_CURRENCY_ENTRY,
	RPC_SEND_TRADER_MANCLASSNAME_ENTRY,
	RPC_SEND_TRADER_NAME_ENTRY,
	RPC_SEND_TRADER_CATEGORY_ENTRY,
	RPC_SEND_TRADER_ITEM_ENTRY,
	RPC_SEND_TRADER_MARKER_ENTRY,
	RPC_SEND_TRADER_DATA_CONFIRMATION,
	RPC_SEND_TRADER_CLEAR,
	RPC_TRADER_MOD_IS_LOADED_CONFIRM,
	RPC_SYNC_OBJECT_ORIENTATION,
	//RPC_SYNC_CARSCRIPT_ISINSAFEZONE,
	RPC_SEND_MENU_BACK,
	RPC_SEND_NOTIFICATION,
	RPC_DELETE_SAFEZONE_MESSAGES,
	RPC_SEND_TRADER_VARIABLES_ENTRY,
	RPC_SEND_TRADER_PLAYERUID,
		RPC_SEND_TRADER_ADMINS_ENTRY,
	RPC_SEND_TRADER_NPCDUMMY_ENTRY,
	RPC_APPRAISE_SELL_REPLY,

	// Звук денег (бумага/купюры) для всех игроков рядом
	RPC_PLAY_TRADER_SOUND,
	RPC_TRADER_BYE,

	// ИИ-торговец: вопрос из чата (!текст) и ответ модели
	RPC_AI_ASK,
	RPC_AI_ANSWER
}